### ISSUE TITLE
Changelog link is incorrect - point to organisation `DerpFest-12` instead of `DerpFest-AOSP`

### ISSUE THREAD

**Issue by Ashvith10** [DerpFest-AOSP/DerpSite#13]
For example, in the case of RMX1971, changelog link points to `https://raw.githubusercontent.com/DerpFest-12/Updater-Stuff/master/changelog_RMX1971.txt` and not `https://raw.githubusercontent.com/DerpFest-AOSP/Updater-Stuff/master/changelog_RMX1971.txt`.

**Comment by NurKeinNeid** [comment]
Fixed
